#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rollbar.PayloadStore;

namespace Rollbar.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20190916220704_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("Rollbar.PayloadStore.Destination", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken")
                        .IsRequired();

                    b.Property<string>("Endpoint")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("Endpoint", "AccessToken");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Rollbar.PayloadStore.PayloadRecord", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConfigJson");

                    b.Property<Guid>("DestinationID");

                    b.Property<string>("PayloadJson")
                        .IsRequired();

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("ID");

                    b.HasIndex("DestinationID");

                    b.ToTable("PayloadRecords");
                });

            modelBuilder.Entity("Rollbar.PayloadStore.PayloadRecord", b =>
                {
                    b.HasOne("Rollbar.PayloadStore.Destination", "Destination")
                        .WithMany("PayloadRecords")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
