// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rollbar.PayloadStore;

namespace Rollbar.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20210908194226_InitialWithScaffold")]
    partial class InitialWithScaffold
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18");

            modelBuilder.Entity("Rollbar.PayloadStore.Destination", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Endpoint", "AccessToken");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Rollbar.PayloadStore.PayloadRecord", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("DestinationID");

                    b.ToTable("PayloadRecords");
                });

            modelBuilder.Entity("Rollbar.PayloadStore.PayloadRecord", b =>
                {
                    b.HasOne("Rollbar.PayloadStore.Destination", "Destination")
                        .WithMany("PayloadRecords")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
